---
name: DDNS-GO
version: "6.17.4"
slug: ddns-go
description: >-
  自动获取公网 IPv4/IPv6 地址，并更新到 Cloudflare、DNSPod 等 DNS 服务商
url: https://github.com/waidosia/hassio-addons/tree/main/ddns-go
image: "ghcr.io/waidosia/ddns-go"
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: services
boot: auto
host_network: true
map:
  - config:rw
webui: "http://[HOST]:[PORT:9876]"
options: {}
schema: {}
